// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsw7dyk0w9MkZGxtjZebvotkQR1BnjNA',
    appId: '1:637875213398:android:188a96b5fab57f4f5957f7',
    messagingSenderId: '637875213398',
    projectId: 'fitness-app-b38a3',
    storageBucket: 'fitness-app-b38a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYXU4dqGzcpmZQlz8W9B5JscLTNy-XTNs',
    appId: '1:637875213398:ios:80a40e0334beaa045957f7',
    messagingSenderId: '637875213398',
    projectId: 'fitness-app-b38a3',
    storageBucket: 'fitness-app-b38a3.firebasestorage.app',
    androidClientId: '637875213398-t4fn23udl8trl3pc0m2finmjjqm25rt7.apps.googleusercontent.com',
    iosClientId: '637875213398-fcki6va20kgm5h7h5r2qev27oi9bhjgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

}